### ISSUE TITLE
Support Parquet file format - Phase 1

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1674]
- [x] support primitive types
- [x] support documented logical types
- [x] support undocumented logical types
- [x] implement ParquetRDD
- [x] bind ParquetRDD to readfile & queryfile

**Comment by rabbitonweb** [comment]
Phase 2 in https://github.com/quasar-analytics/quasar/issues/2215
