### ISSUE TITLE
Provide new connector: spark-elastic

### ISSUE THREAD

**Issue by rabbitonweb** [quasar-analytics/quasar#1675]
- [x] Running Elastic connector (runnable in UI)
- [x] Create workspaces
- [ ] Integration tests 100% passing
- [x] Spark cluster configurtion (memory, executors, etc)
- [ ] Deal with illegal chars in ElasticSearch (white spaces, leading _ etc.)
- [x] Ability to configure ES parameters (host & port)
