### ISSUE TITLE
Smart Caching

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1714]
**Server-Side Cache Settings.** If cache settings can be specified by the client, and satisfied by the server, then much more consistent and broadly performant user experiences can be created. At minimum, views should be cach-able, with cache settings as supported by HTTP.

SQL<sup>2</sup> views should support cache settings modeled after the HTTP Cache-Control directive.

```
Cache-Control: max-age=
Cache-Control: max-stale[=]
Cache-Control: min-fresh=
Cache-control: no-cache 
Cache-control: no-store
Cache-control: no-transform
Cache-control: only-if-cached
```

If a SQL<sup>2</sup> view is cached, then an attempt will be made by the server to execute the query and save the results. Ideally, a job tracker would keep track of all cached SQL<sup>2</sup> views, and ensure they do not fall badly out of date, by executing queries and caching the results in order to satisfy the cache parameters.

The job tracker should utilize Quasar's relational database for storing and tracking the status of jobs (this implies migrating the relational backend from Advanced to Community, which no longer needs to utilize a configuration file for storing mount information).

An assumption should be that multiple Quasar's are running and therefore the search for pending jobs should be done in a concurrent-safe fashion,  utilizing atomic database guarantees to ensure no two Quasar instances are running the same job.

### Permissions

Retrieving cached data should not count as requiring write permission, even if writeback is used to materialize results from a cached query.

**Comment by drostron** [comment]
- [ ] Bring MetaStore support from QAdv to Quasar #1888
- [ ] View Cache Job tracker #1889 
- [ ] Update view handling per caching #1890 
- [ ] QAdv: Switch to Quasar MetaStore slamdata/quasar-advanced#148
- [ ] QAdv: Update permission system per cached views slamdata/quasar-advanced#149

**Comment by jdegoes** [comment]
@drostron Let's also have a kick-off meeting on this next time we're both in the office.

**Comment by drostron** [comment]
@jdegoes Sounds good

**Comment by zeeiyerWork** [comment]
@jdegoes fyi -> Talked to @drostron last week.

Discussed a few things (primarily around things folks expect from a caching implementation -> declarative TTL/TTI, Cache-Priming (Cache Job Tracker) + Lazy Loading, Spilling to Off-Heap Storage or local disk or Server Side + Operational Ease around runtime manipulations of cache). As such several may therefore have invested in a MemcacheD, Alluxio, Terracotta-Ehcache, Hazelcast, etc. etc. Hence presumably the need to have an interface and implement to that interface.

e.g. Slam Virtual File System operations of Create/Delete/Write-Update/Read might translate to Cache Creation/Deletion/Put or Get/Put, Remove etc. So it would be good to be able to come across to end-users as some one who plays well with the ecosystem - i.e. you don't need to use our cache implementation. WE maybe have one example of how we integrate to a 3rd party cache (e.g. Ehcache or Alluxio or something) and others can build on that example. (Similar to the desired connector architecture).

**Comment by zeeiyerWork** [comment]
Also asked @drostron to investigate what it would take to show an example integration to a 3rd party cache (e.g. Ehcache). Feel that the minute one implements a cache, consumers want statistics (cache hit ratio, cache size, histograms around cache population etc.) and control (e.g. blowing away the cache) etc. Hence the value to integrating to a 3rd party cache, which is already fully-baked. Further shows that we play well with the ecosystem, instead of sending the message that we want the market to adopt our ways. Further, Devops teams at enterprises prefer to learn and standardize on certain components of the infrastructure, instead of having to learn behaviors, peculiar to a non-specialized vendor. Of course, having a simple implementation native to Slam (i.e. our FS) is helpful for those who want a single stop shop.

**Comment by jdegoes** [comment]
@zeeiyerWork IMO there is no point in investigating that right now without the fallback evaluator. If the result set is not stored inside the database, then we cannot perform any computation on it. The front-end assumes that any cached data set can be further transformed. Therefore, supporting an external cache is not really possible in any useful way until the fallback evaluator has been completed.

When the fallback evaluator has been completed, if a result set is stored in an external cache such as EHCache, then we can perform further computation by simply using the fallback evaluator. That may or may not be faster than performing further computation inside the database depending on indices, etc., but at least it will be possible with the fallback evaluator in place.

**Comment by zeeiyerWork** [comment]
Thanks for the clarification - understood, I think. Although it seems we have 2 use-cases. 
1. A Slam-Data mutable cache
2. A Slam-Data "terminal-state" cache - where this is the end result of a set of cards - and we we don't want a new user accessing this pipeline to execute everything, but just get to the final result/report/visualization when this kind of a 3rd party cahe makes sense. e.g. parity with the [Looker Cache]( https://discourse.looker.com/t/query-caching-behavior-in-looker/158))

IT seems that the current spec only focuses on (1), although we do need (2), when multiple users can access the same result without going through all the intermediate compute.

**Comment by zeeiyerWork** [comment]
@drostron -> So based on this am conversation, it appears that in the short-term:
1. There is no change to the current implementation - caches simply get written to the target store being referenced in the mount point. Failure to write due to insufficient privilege, should be communicated to the front-end, so end-users can be presented with a useful and actionable error message. 
2. In the longer term, there is a possibility to persist this cache within Mimir and consider certain queries as federated between Mimir and the target store specified in the mount point. It may also be possible to interrogate the connector to its ability/preference to host cache content. 

Please acknowledge or state any differences of opinion here, so we can seek additional clarification, if needed.

**Comment by drostron** [comment]
@zeeiyerWork Sounds reasonable and summarizes today's discussion.
