### ISSUE TITLE
Statistical Structural Types: Phase A

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1715]
**Statistical Structural Types**. Having a performant, responsive means for the front-end to obtain increasingly accurate statistical information about the structural characteristics of a data set will enable much improved user-experiences, and improve the fidelity of front-end experiences that currently rely on a (non-random) sample of a small number of values from a data set.

Statistical structural types describe, in a structured and statistical representation isomorphic to SQL2's pattern language, an underlying data set in a compressed way.

1. **Representation of Types**. We need a serialization format for annotated types (probably EJSON-based, unless there's a compelling reason otherwise). 
2. **Augmented Type System**. The existing type system is probably sufficient for a "v1", but may need small augmentation — for example, the ability to describe a map whose keys all have the same structural type.
3. **Compression Algorithm**. We need an ANALYZE function which goes over a data set and describes the type of all data seen, in a lossy way. There is no single way to perform compression. We should investigate different heuristics for performing the compression.

In theory, something like `Cofree` could be used over a fixed point representation of types in order to provide statistical annotations without requiring a parallel hierarchy.

**Tasks**
- [x] Fixpoint representation of LogicalPlan types (#1944)
- [x] Analysis that builds a structural type from a dataset annotated with statistical information
- [x] Lossy Compression algorithm for SST providing control over how much information is discarded (#2022)
- [x] Means of obtaining a sample of a dataset at a given path
- [x] `EJson` serialization format for types
- [x] HTTP endpoint returning SST for the dataset at the given path

**Comment by wemrysi** [comment]
@jdegoes Is there a description/specification of "SQL2's pattern language" I can refer to?

**Comment by wemrysi** [comment]
Found these in JIRA, which look promising

https://slamdata.atlassian.net/browse/SD-1009
https://slamdata.atlassian.net/browse/SD-1010

**Comment by beckyconning** [comment]
When this is done please notify #frontend : ) Thanks! : )

**Comment by wemrysi** [comment]
@beckyconning Sure thing!

**Comment by zeeiyerWork** [comment]
@wemrysi  -> To our discussion of stuff just being in people's heads, could be break down to a more fine-grained level. Basically, trying to understand the ETA, when @beckyconning can jump on this from the front-end POV. Also if any of these sub-tasks can be assigned to Juan Pablo or Nic, let me know. ...Thanks.

**Comment by zeeiyerWork** [comment]
@wemrysi , @beckyconning  -> Also, do we intend to provide a parameter to control scope of discovery (i.e. default = Qscript picks a sample of 1000 records), But can front-end override that behavior, by asking the backend to either pick top/random 5000 or N or specify that the discovery be based off the entire data-set.

**Comment by wemrysi** [comment]
@zeeiyerWork There are some tasks in the description that break this epic down a bit, some of which are reasonably fine-grained (serialization, need for an http endpoint, fixpoint repr of type) and the others less so as what those tasks actually involve isn't quite clear yet. I plan to create individual issues for them as I begin work to track progress/discussion on them like I did for #1944.

As for controlling the scope of discovery, it would seem that some control over the process could be useful, though I'd be interested in the reasons why one would want said control as the answers to this may allow us to provide more declarative knobs (i.e. desired accuracy, latency of response, etc).

**Comment by jdegoes** [comment]
The front-end has no way of knowing whether 1000 records is meaningful or not. Essentially, the front-end can provide requested latency bounds, and the backend can do whatever it thinks will retrieve the SST in the desired amount of latency. In addition, the front-end can and should provide "compression settings" indicating how much information the front-end wishes to use in describing the SST (how this is described depends on the exact algorithm chosen for compression).

However, I'd view both of these as enhancement to a core feature that chooses any sample size (e.g. 1000) that can be returned at interactive response times (< 2 seconds).

**Comment by zeeiyerWork** [comment]
![image](https://cloud.githubusercontent.com/assets/24783629/24118343/0b06a062-0d73-11e7-859c-241011374536.png)
Agreed - that this is an enhancement to the core feature. Lmk, if capturing it here is confusing - my goal was to capture it, so it does get lost in some google doc. 
And yes, this is from the PERSONA of an Advanced User/Administrator, who may want to specify where on the LATENCY versus COMPRESSION-LOSS decay graph, they wish to lie, instead of SlamData just picking a point for them. Either through the UI or via SQL**2.
I suppose, this could be communicated to a LAY-end-user in the UI, but will take a fair bit of work to hide the complexity (based on the store/schema in play - i.e. no value in case of structured-schema and some cost/benefit ratio in case of unstructured schema).

**Comment by sellout** [comment]
At least in (newer versions of) Mongo you can `$sample` the whole collection and get back a cursor to the collection with the documents in a random order. Which would let us effectively keep refining our response by processing the stream until we hit the time limit.

I don’t know 1. how the performance on reading 1k records this way compares to `$sample(1000)`, or 2. if this sort of thing is generally available on other stores. But it seems like a nice approach when possible, rather than guessing up front how much we’ll be able to process (given dynamic load on the store, etc.).

**Comment by wemrysi** [comment]
@jdegoes Do SSTs need to reflect metadata in the dataset as well? From a typing perspective the current thinking is that only the value determines the type, but is that also true structurally?

**Comment by jdegoes** [comment]
@wemrysi I don't think we need that, at least not now. Since you can always lift metadata into the value level and ask for the schema of that.
