### ISSUE TITLE
Basic Query Analysis

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1716]
**Query Analysis**. Users have no idea the impact of their queries. Even basic query analysis could help provide sensible feedback to the SlamData user-interface, as well as the user, on whether they can expect to wait seconds, minutes, or hours; and on the load exerted on the data source by the query.

SlamData can make much better decisions if it knows how complex a query will be to execute.

* **Instant** — There is negligible cost to execute the query.
* **Interactive** — There is some cost to execute the query, but only in the range of a few seconds to low tens of seconds.
* **Semi-Interactive** — The query will execute in minutes.
* **Batch** — The query requires hours or days to execute.
* **Unknown** — There is no possible way to estimate how much time executing the query would require, without actually executing it and measuring the result. **This should be used sparingly by connectors as it provides no information to the front-end.**

This functionality has to be pushed into the connector, since there's no way anything higher could know how long a given query would take.

This should be incorporated into the explain-type API which compiles the query.

- [x] QA typeclasss to collect info about qscript template
- [x] Implement Cardinality typeclass
- [x] Implement generic Cost typeclass
- [x] change `pathCard` to return `M[Int]`
- [x] Implement generic `pathCard` that uses `QueryFile` interpreter & does simple `select * from x`
- [x] mapping cost value to `AnalysisResult` - a manual, explicit tuning
- [x] add REST endpoint /analysis

**Comment by rabbitonweb** [comment]
- [ ] QA typeclasss to collect info aobut qscript template

- [ ] Implement QA typeclass

- [ ] Implement QA algebra for sparkcore

- [ ] Implement QA algebra for makrlogic

- [ ] Implement QA algebra for couchbase

**Comment by rabbitonweb** [comment]
This issue is closed.

With a rise of brand new `BackendModule` we will need to add implementation for it. For details look in https://github.com/quasar-analytics/quasar/issues/2213
