### ISSUE TITLE
epic: Fallback evaluator Initial Implementation

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1732]
The fallback evaluator is a generic term used to refer to a new connector that targets the resurrected [Precog analytics engine](http://github.com/precog/platform), updated to work with the (slightly) extended data model supported by Quasar.

For purposes of this ticket, the fallback evaluator shall be a full-fledged connector, capable of storing, updating, deleting, moving, and querying JSON files. These files shall be stored local to the Quasar server, in a directory chosen by configuration of the fallback evaluator, and in a fashion similar to the Spark Local connector.

## Phase 1

The first phase of the project is to create a minimally-viable product that leverages the Precog analytics engine, and involves the following steps:

- [x] Resurrect the Precog analytics engine for the current version of Scala, trimming out unnecessary dependencies and replacing unmaintained but necessary dependencies
- [x] Replicate the Spark Local connector to a new fallback evaluator project
- [ ] Instead of compiling QScript to an `RDD[Data]` representation, compile to a `Table` representation, using `TransSpec` for `MapFunc` operations, and (probably) using the existing sorting mechanism for performing equi joins.
- [ ] Make all integration tests pass for the connector
- [ ] Add configuration for the connector
- [ ] Ensure the SlamData front-end is fully functional with the new connector

Note that in the first phase of the project, some queries may fail if they would otherwise require extensions to the Precog analytics engine (e.g. arbitrary data in the keys of maps).

## Phase 2

The second phase involves generalizing the data model of the Precog analytics engine, and improving the performance of the connector.

- [ ] Generalize the Table data model to include data types supported by MRA, including maps with non-string keys and metadata (and anything else?)
- [ ] Resurrect NIHDB for storing data, and generalize its data model to EJSON (together with a binary, columnar encoding of EJSON). NIHDB is an order of magnitude faster than JSON and permits selective loading of relevant columns.
- [ ] Remove all laziness from Table. Currently, the table abstraction lazily computes values, operating as a function from row number to value. This is very inefficient, and benchmarks indicate that performance can be improved by several factors by switching to an eager evaluation at the level of each chunk (using while loops or other low-level mechanism to compute the contents of each chunk).
- [ ] Push arrays to leaves. Arrays can be pushed into array primitives at leaves by tracking the metadata appropriately and adding new support for such primitive types at the leaves. This will make many array operations very fast, as well as make the metadata of tables much more compact.
- [ ] Support other join types. Currently, tables are joined by crossing or by sorting and cogrouping. However, in many cases, a hash or other type of join might be more appropriate (or even creating in-memory indexes in some cases).

---

- #2855 
- #2776 
- #2765 
- #2692 
- #2697
- #2675 
- #2674 
- #2669 
- #2656
- #2642
- #2618 
- #2570
- #2558
- #2534 
- #2520
- #2518
- #2506
- #2487
- #2485
- #2483
- #2482
- #2481
- #2439
- #2438
- #2421
- #2334
- #2268 
- #2267
- #2266
- #2265
- #2254
- #2253
- #2251
- #2249
- #2248
- #2242
- #2218
- #2211
- #2207
- #2206
- #2174
- #2171 
- #2136
- #2069
- #1992
- #1991
- #1990
- #1989
- #1988
- #1987

**Comment by paulp** [comment]
Thanks a lot for providing this structure.

**Comment by zeeiyerWork** [comment]
Chatted with @djspiewak last week. Of course, we need to get past Phase-1 by the April time-frame,  given heightened expectations from the business. 

But 1 question/issue presumably for a phase2 is about how this will play with SlamD HA. In that               
>>> These files shall be stored local to the Quasar server....
So does NIHDB offer a HA configuration, or does this mean that we need to advise customers for whom HA matters, to use Shared-Disk (NFS-mounted or SAN or S3 or ....)  - or do we just live with he fact that you might have to recreate NIH-db should you lose the local SlamD server.

**Comment by jdegoes** [comment]
It will definitely not be highly-available in the initial release. Quasar Clustering can use replication to achieve this, or in the interim, customers can use an HA file system.

**Comment by zeeiyerWork** [comment]
The 1st phase is likely to finish the following in the 4.2 iteration (see related Gist @ https://gist.github.com/djspiewak/0bea536a6658589c5e4138d950e44ae4) 
- Backend Abstraction
- Coalescence
- Simplifications
- Implementation in existing connectors (Marklogic, Couchbase, Spark, Maybe Mongo?)

Then we get to the next set of issues....The ones included as of today and (Scheduled for may2017 and june2017 iterations) =
#1991 
#1990
#1989 
#1988  
#1987
