### ISSUE TITLE
Add SQL2 Functions — AKA Parameterized Views (DRAFT)

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1792]
Currently, views may contain holes (variables), but these must be fully specified at creation time. Any attempt to update the values in the holes results in updating the view. This usage workflow is good for some purposes but wholly inadequate for interactive dashboards designed to be used by lots of users.

To address these problems, we need to introduce parameterized views, which are views that contain holes whose values are not specified until the result set is read from Quasar. This will allow front-end applications such as SlamData to store the parameterized views only, and then on a per-user basis, specify values for holes.

In addition, this opens the door to more advanced forms of caching, such as cubing.

## SQL<sup>2</sup> Syntax

A parameterized view, AKA a *process*, is a function from a one or more named values to a result set.

```sql
CREATE FUNCTION FLOOR(:num)
BEGIN
  :num - (:num % 1)
END;

CREATE FUNCTION ROUND(:num)
BEGIN
  FLOOR(:num + 0.5)
END;
```

An ordinary view emerges as a special case of an immediately applied function:

```sql
CREATE FUNCTION ANON123(:source)
BEGIN
  SELECT first_name, last_name FROM :source
END;

ANON123(`/foo/bar/baz`)
```

There are two top-level grammers we will need to support:

 * Mixing let bindings with function declarations followed by a terminal expression, which allows users to define and use their own functions inside their own queries;
 * A pure module that consists only of function declarations and possibly let bindings.

## File System: Module Nodes / Mounts

Parameterized views could piggyback off view mounts or new type of node in the file system (*module nodes*, which contain SQL<sup>2</sup> functions that accept input and return output). As with mounts, reading from module and editing their configuration are separate, until the two have been unified via metadata or other mechanism.

A module is akin to a directory of named executables (each defined by a SQL<sup>2</sup>), whereas a data node is akin to a data file, and a directory node is the same across the Quasar file system and ordinary file systems.

If the SQL<sup>2</sup> defining a module defines multiple functions, then the module node contains multiple named executables. In this sense, a module groups together a bunch of functions under a common namespace.

## Process API

Module may need a new API to retrieve results from, such as `/process/fs/<location>/<name>` (alternatively, the existing GET API can be returned but variables can be required to have valued specified in the request). A `POST` should be required to run a process inside a module, and the body of the post must be JSON / EJSON which specifies values for all named parameters. For example:

```json
{"num": 2.3}
```

## Metadata API

Retrieving metadata on a module should specify the names of all functions (in the directory listing of the mount?) and the number and types of parameters required by all the functions. This will enable front-ends built on top the API to prompt for appropriate inputs to each of the functions.

## Imports

No doubt, one of the first things users will want (after they can create functions) is to be able to import them across different queries. We should think about whether to define that here or defer to later. At least for the initial bare bones implementation, users could copy/paste definitions in each SQL file, which seems like a reasonable if painful workaround.

```sql
import `/foo/bar/baz/`;
```

## Caching

**Notes on Caching**: Not intended to be implemented in 4.2.

Caching a parameterized view is equivalent to computing all possible values for all parameters, and running the query for each value. In practice, using `GROUP BY`, the process can be collapsed into a single query.

Caching requires the determination of the possible values for all parameters (which can yield a non-empty result set). This is an algebraic problem that may or may not have a solution depending on the query.

For example, the following function may not be cached:

```sql
CREATE FUNCTION ARRAY_LENGTH(:foo)
BEGIN
  COUNT(:foo[_])
END
```

The reason the function may not be cached is because the number of solutions for `:foo` which produce a non-empty result set is infinite.

However, the following function may be cached:

```sql
CREATE FUNCTION USER_DATA(:user_id)
BEGIN
  SELECT * FROM `/root/path/data/` WHERE user_id = :user_id
END
```

In this case, the number of solutions for `:user_id` which produce a non-empty result set is finite, and can be determined by distincting the `user_id` field in the source data set.

Such a function may be cached efficiently through generation, execution, and indexed storage of the following query:

```sql
SELECT{"variables": {"user_id": user_id}, "result_set": [* ...]} 
  FROM `/root/path/data/` 
  GROUP BY user_id
```

If such a result set has an index on `variables.user_id`, or if the result set is stored as a map from variables to results, then lookups / evaluation of the function become `O(1)`.

Note that even partial solutions for a parameterized view can accelerate results. But if no part of a parameterized view can be cached, then acceleration is going to require more traditional techniques (storage in memory, indexing on relevant fields, incremental computation, etc.).

## Subtasks

- [x] Extend SQL AST and enhance compiler to apply SQL functions
- [x] Extend SQL parser to support user-defined functions and imports
- [x] Extend SQL parser to parse modules (i.e. lets+functions without terminal expressions)
- [x] Introduce module (mount?) in file system
- [x] Support file system operations (metadata, etc.) for module type
- [x] Enhance metadata API for module (mount?) & functions in module
- [x] Introduce evaluation API for functions in module (or reuse GET API but require params)
- [x] Update permission system for module (if necessary)
- [ ] Implement support for imported modules (final task)

**Comment by jdegoes** [comment]
@beckyconning Please review.

**Comment by jdegoes** [comment]
Technical review & final specification by @sellout

**Comment by jedesah** [comment]
My estimate (in 8 hour days) for the sub-tasks:

- 4 days
- 2 days
- 1 days
- 3 days
- 2 days (if necessary)
- 4 days
- 3 days
- 2 days
- 4 days

**Comment by beckyconning** [comment]
Didn't see this @. I'm reviewing now.

**Comment by beckyconning** [comment]
Is the intention that the following would work?

Access the folder `/`
Create a new MongoDB mount named `test-mount` with the database `testDb`
Access the folder `/test-mount/testDb`
Create a folder named `processes`
Access the folder `/test-mount/testDb/processes`
Create a new SQL² mount named `userData` with the query
```
CREATE FUNCTION USER_DATA(:user_id)
BEGIN
  SELECT * FROM `/root/path/data/` WHERE user_id = :user_id
END
```
Access the folder `/test-mount/testDb`
Create a new workspace named `User`
Rename the unnamed deck to `User Id`
In the deck named `User Id`
  Insert a Build Variables Card
  Add number variable `user_id` with default value `0`
  Insert a Show Variables Card
  Wrap the deck named `User Id`
Rename the unnamed deck to `User`
Mirror the deck named `User Id`
Rename the unnamed deck to `User Table`
In the deck named `User Table`
  Insert a Query Card
  Provide the query
  ```
  import `/test-mount/testDb/processes/userData`;
  userData(:user_id)
  ```
  Insert a Preview Table Card

**Comment by jdegoes** [comment]
@beckyconning This is basically correct, except it would be a SQL<sup>2</sup> *module* mount, not a *query* mount. However, the main use of this will not initially be in user-imported modules, but rather in the front-end translating queries that use variables into modules, and then supplying values for those variables at query time. In this way, variable values can be separated from anything in the file system (including module mounts, etc.), which means they can be stored in user-storage and updated independently by many concurrent users. The one detail we should try to hammer out ASAP is how scoping will work in the presence of modules, maybe pull in Nathan into that conversation.

**Comment by beckyconning** [comment]
Cool. The primary intention for this to be used via the API by SlamData to allow for read only deck consuming is clear. I wasn't sure about this secondary use case but this clarifies it. So to support this secondary use we would need to add a mount type for SQL2 Modules.

This all seems to make sense.

If I understand correctly the way this would be used in the front end is that module(s) would be created which contain processes which represent views during deck authoring. All views will be represented as processes.

Cards can be chained by creating processes expressed in terms of another process which take all the arguments required for the subexpression.

Then during deck evaluation rather than using `IMPORT` each process will be called via the HTTP API.   Following the spec above an example of this may be

```
-- /mount/db/workspace/processes/aa8sdf798a7 created by the authoring of a Query Card
CREATE FUNCTION aa8sdf798a7(:country, :event)
BEGIN
    SELECT * FROM `/mount/db/olympics` WHERE country = :country AND event = :event
END;
```

```
-- /mount/db/workspace/processes/akljsd8a92 created by the authoring of a Query Card which follows the prior query card
IMPORT `/mount/db/workspace/processes/aa8sdf798a7`;
CREATE FUNCTION akljsd8a92(:name, :country, :event)
BEGIN
  aa8sdf798a7(:country, :event) WHERE name = :name
END;
```

Then during evaluation the following HTTP request would be made using the variables provided

`GET /test/workspace/result/akljsd8a92?name=Mo Farah&country=UK&event=100 Metres Sprint`

This would allow for evaluation with only “View” permissions and therefore deck consuming with only “View” permissions as well as the provision of locally stored values for these variables.

Would there be one module per workspace, one module per deck or one module per process?

Perhaps processes will be named after the card they were created to serve.

**Comment by garyb** [comment]
@jdegoes is there a separate issue for enhancing compile to be able to provide information about a query's dependencies on processes, or is that a subtask that should belong in here too?

**Comment by jdegoes** [comment]
@garyb We need to make a separate task. 

I assume you want compile to report on whatever module imports are in the query? Or something else?

**Comment by jdegoes** [comment]
I would only use modules for views with variables. For views without variables, I think better interaction will be achieved with ordinary view mounts.

**Comment by garyb** [comment]
> I assume you want compile to report on whatever module imports are in the query? Or something else?

If we could get both imported modules and the functions used that'd be ideal I think.

> I would only use modules for views with variables. For views without variables, I think better interaction will be achieved with ordinary view mounts.

Yeah, our intention was to do that - although as soon as a parameterized view is introduced in a chain of cards every view after that will also have to be a paramtereized view I think, since we'll need to propagate variables backwards from the "end".

**Comment by jdegoes** [comment]
@garyb See [here](https://github.com/quasar-analytics/quasar/issues/1941) and please add or clarify depending on your needs.

**Comment by beckyconning** [comment]
@jedesah hi! would you be up for talking me through where you're up to and what you've got left at some point today or on monday?

**Comment by jedesah** [comment]
@beckyconning Happy to do so! How about we do that on Monday. In case you didn't notice already, I've been check marking the subtasks that are done. Although, unfortunately, a few of the ones marked as done have not yet been merged to master (we're still are pretty bad about review times)

**Comment by jedesah** [comment]
Everything is done and in master except for imports. Will move this whole issue to May iteration to track work on imports though instead of creating a new issue for them.
