### ISSUE TITLE
Deprecate old-Mongo-connector-implementation and switch to new-Mongo-connector

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#1940]
Based on QScript etc.

**Comment by zeeiyerWork** [comment]
Since this is a mega-mega project, @jdegoes suggests breaking this down into more fine-grained tasks - @sellout can you please do that? <Thanks>

**Comment by sellout** [comment]
These apply upstream of the connector, but fix issues that make it difficult to generate plans that are competitive with pre-QScript Mongo.
- [ ] apply PruneArrays to branches
- [ ] fix provenance on autojoins (#1929, #1951)

These are Mongo-specific.
- [ ] fix remaining failing integration tests (unless they also fail on old Mongo)
- [ ] compare timing of planning+execution between old and new Mongo, improving the latter as necessary

I expect the switchover may happen before the last step is complete. At which point, we can identify queries that still underperform and make individual issues for them.

**Comment by alissapajer** [comment]
Tickets for `PruneArrays` work are #1794 and #1793.

**Comment by alissapajer** [comment]
Everything here is covered in other issues so I am closing this. 

We need to have a separate discussion about what performance testing needs to be done on new mongo and when that should be done. Connector performance is affected by qscript compilation performance, so I expect most performance work (at least for new mongo) will be on qscript.
