### ISSUE TITLE
epic: Connector: New Mongo Preparation Work

### ISSUE THREAD

**Issue by jdegoes** [quasar-analytics/quasar#1954]
This is an epic ticket to track a series of upgrades that we need to make to the MongoDB connector.

Where functions do not exist in the standard library, they should be added to the standard library and crafted to follow PostgreSQL conventions, subject to the following caveat: 

 * Functions that can be implemented in terms of other more elemental functions (e.g. `floor x = x - (x % 1)`, `ceil x = if (x % 1 == 0) then x else floor (x + 1)`, `round x = floor (x + 0.5)` should be implemented like this; then we can rely on custom extractors to reconstruct and optimize their occurrence in the connector-exposed QScript. This way connectors need to deal with a non-elemental function only if they have the capability and interest in handling it.
 * In cases where an elemental function does not exist but could exist (e.g. a function to convert a decimal to an integer), they should be added to the standard library, and supported for all other connectors.

We will have to generate different MongoDB code for different versions of the database (2.6 - 3.6).

## Hacks

 - [ ] Leverage `$substr` to convert from numbers to strings, and avoid map/reduce

## Joins

 - [ ] Optimize `LEFT JOIN` to `$lookup`, not just `JOIN`

## Pipeline Operators

 - [ ] Support `$geoNear` as a series of functions modeled after PostgreSQL GIS functions
 - [ ] Support `$facet` to avoid propagating information through reductions
 - [ ] Support `$bucket`
 - [ ] Support enhanced `$unwind` — There are options to preserve empty/null arrays, and to include the array index (useful for generating array indices)
 - [ ] Support `$bucketAuto` — Could be some `ANALYZE` / `HISTOGRAM` type function
 - [ ] Support `$sortByCount` — Support as an optimization of counting / group by
 - [ ] Support `$replaceRoot` — This will enable eliminating `value` from output
 - [ ] Support `$graphLookup` — This will require new syntax / function in SQL<sup>2</sup>

## Schema

MongoDB 3.2 and later have [optional schema](https://docs.mongodb.com/manual/core/document-validation/), which can be used to accelerate statistical-type inference, as well as produce better error messages about broken queries.

 - [ ] Accelerate SSTs with optional schema
 - [ ] For queries over collections with schema, fail out unproductive queries
 - [ ] Remove runtime type checks when optional schema indicates they aren't necessary

### Set Operators

 - [ ] Support `$setEquals`
 - [ ] Support `$setIntersection`
 - [ ] Support `$setUnion`
 - [ ] Support `$setDifference`
 - [ ] Support `$setIsSubset`
 - [ ] Support `$anyElementIsTrue`
 - [ ] Support `$allElementsTrue`

### Arithmetic Operators - see https://github.com/quasar-analytics/quasar/issues/2272

 - [ ] Support `$abs`
 - [ ] Support `$log`
 - [ ] Support `$log10`
 - [ ] Support `$ln`
 - [ ] Support `$ceil`
 - [ ] Support `$floor`
 - [ ] Support `$trunc`
 - [ ] Support `$sqrt`

### Text Search

 - [ ] Support `$meta` — Support as `META(<text search expression>).textScore`

### String Operators 

 - [ ] Support `$indexOfBytes`
 - [ ] Support `$indexOfCP`
 - [ ] Support `$split`
 - [ ] Support `$strLenBytes`
 - [ ] Support `$strLenCP`
 - [ ] Support `$strcasecmp`
 - [ ] Support `$substrBytes`
 - [ ] Support `$substrCP`

### Arrays

 - [ ] Support `$slice` — Support as `[foo[0 .. 2] ...]` (requires a change to semantics!)
 - [ ] Support `$range` — Support as `0 .. 2`
 - [ ] Support `$reverseArray`
 - [ ] Support `$indexOfArray` — Support in pattern matching
 - [ ] Support `$reduce` — Support as ???
 - [ ] Support `$zip` — Support as `[[foo[_], bar[_]] ...]` or equivalent, and useful when generating array indices
 - [ ] Support `$map` — Support as ???

### Variables

 - [ ] Support `$let` to improve performance for duplicated subexpressions

### Date Operators

Anything new to support?

### Conditional Operators

 - [x] Support `$ifNull`
 - [ ] Support `$switch`

### Data Type Operators

 - [x] Support `$type`

### Reductions 

- [ ] Support `$stdDevPop`
- [ ] Support `$stdDevSamp`
- [ ] Support all aggregations on a non-grouped set at the top level by taking advantage of the fact that accumulators can now be used in `$project` phases

### Security

 - [ ] Support SSL from API configuration (TBD: Also requires SD ticket)

**Comment by sellout** [comment]
Things like `$reduce` and `$map` on arrays need to be identified as `LeftShift; Reduce` and `LeftShift; Map; Reduce(UnshiftArray)` patterns in QScript. May even be worth adding a transformation to QScript for that.

I _thought_ `LEFT JOIN` (and `RIGHT JOIN`) already used `$lookup` when possible, but I could be wrong.

Why does `$slice` require a change to the semantics of `[foo[0 .. 2] ...]`?

**Comment by jdegoes** [comment]
> Why does $slice require a change to the semantics of [foo[0 .. 2] ...]?

Because `0 .. 2` produces a set, which means `foo[0 .. 2]` is equivalent to `foo[0] UNION ALL foo[1] UNION ALL foo[2]`, which means if you try to reduce it, it will reduce the entire set into an array. Instead, it would be ideal if `foo[0 .. 2]` added a new dimension comprised of the index (a project-index type operation), allowing subsequent array reduction to eliminate the dimension, which would allow slice to be expressed as `[foo[0 .. 2] ...]`.

**Comment by jdegoes** [comment]
@zeeiyerWork This is an epic and will have to be broken into lots of tickets, probably multiple engineers working on this will be required to ship this by end of Q3.

**Comment by jdegoes** [comment]
@zeeiyerWork Not all of these have been broken out into separate tasks.

**Comment by zeeiyerWork** [comment]
@jdegoes -> that is being executed as of now along with others beyond what was originally described in the Epic Description ->  to arrive at a "github" based definition of "done" (or MVP) for the new Mongo connector...

**Comment by zeeiyerWork** [comment]
@jdegoes -> @sellout and team need the following clarifications:

- [ ] Data Type Operators: $type -> Is already supported? Is anything else needed? 
- [ ] Conditional Operators: $ifnull is already supported? So, just add $switch? 
- [ ] Set Operators: -> All mentioned here already supported? is anything else needed?
- [ ] Hacks Leverage $substr to convert from numbers to strings, and avoid map/reduce -> $substr is deprecated it seems from 3.4 based on mongodb documententation - just replaced with $substrBytes - although unclear how it avoids map/reduce?

**Comment by jdegoes** [comment]
1. $type is not utilized. We use total ordering to infer types, but this is slow compared to using $type in versions of MongoDB that support it.
2. It's not supported.
3. Definitely not supported.
4. $substr can be used to convert a number to a string in older versions of Mongo that do not support this natively. Currently we degrade to map/reduce in such cases, which is unacceptably slow.

**Comment by sellout** [comment]
1. Was `$type` added as an expression operator? We do use `$type` in selectors. We only use total ordering when we’re forced to represent it in expressions. There is a change on the new Mongo branch that extracts more guards into filters, although I’m not sure whether to apply this simply to joins (since the guards generally can be applied as pre-filters), or to all cases (like maps), or to leave the latter up to the connectors.
2. `$ifNull` is implemented in the connector, but we never generate it in a plan. We need to identify patterns like `IfUndefined(Cond(Eq(Null, x), y, Undefined), y)` (or something like that) and turn those into `$ifNull` (since MRA’s Null semantics are different from Mongo’s) and then also have SQL² `is null` generate something like that pattern instead of just `Eq(Null, x)`.
3. As with 2, they’re implemented in the connector, but never generated. These mostly would benefit from QScript transformations, since these are currently represented by dimensional transforms and having optional MapFuncs that offer these directly to connectors that want them would make it simpler.
4. _How_ do you use $substr to convert a number to a string? Do you iterate over the digits, repeatedly dividing by 10, and then get the char from `"0123456789"`? The hitch is that I don’t _think_ there’s an iteration facility in Mongo expressions. There’s `$map`, but we’d still need to iterate to separate the digits.

**Comment by jdegoes** [comment]
1. Yes, it's an expression operator in new versions.
2. In MRA, null is a sentinel value, it's  not 3VL like SQL (that'd be `undefined`).
3. Agreed.
4. `$substr:["$foo", 0, -1 ]` will convert a `foo` number to a string in older versions of MongoDB. This is an undocumented hack.

**Comment by sellout** [comment]
2. Yeah – SQL and Mongo have similar null semantics, so it’s the converting back and forth through MRA that needs to be implemented.
4. Wow 😱

**Comment by zeeiyerWork** [comment]
All the issues in this epic have been closed. The description has been decomposed into multiple Epics and Issues there in. Other epics that relate to this topic are still in progress and are underway and include https://github.com/quasar-analytics/quasar/issues/2500 and https://github.com/quasar-analytics/quasar/issues/2503 respectively.

This Epic is therefore being closed.
