### ISSUE TITLE
Lossy Structural Type Compression Algorithm

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2022]
In order to provide a summary of the structure of a dataset in a space-efficient way, we need to compress the information extracted.

We'd also like to be able to tune how this compression is performed via parameters to give users control over how much information is discarded, probably via specifying space bounds on the resulting structural type.

- [x] Stats annotation for SST
- [x] Entropy/information content function for SST
- [x] Long string compression (compress strings longer than a threshold to `char[]`)
- [x] Binary compression (compress binary values to `byte[]`)
- [x] Union value compression, maybe with threshold or top-k preservation
- [x] Map key compression

**Comment by wemrysi** [comment]
The current approach/thoughts on this are to construct an annotated tree representing a type full of literals/consts at the leaves, accumulated in unions where they differ. We'd then compress this structure where compression would mostly mean reducing the size of these unions.

For example, merging these data
```
{"foo" : "bar", "baz" : 1, "quux" : [42, 7]}
{"foo" : 34.23, "baz": 1, "quux": [4, 5, 123]}
```
would result in
```
2#{
  "foo" : 2#(1#"bar", 1#34.23),
  "baz": 2#1,
  "quux": 2#[
    2#(1#42, 1#4),
    2#(1#7, 1#5),
    1#123
  ]
}
```
Where `N#` represents the number of times that value was observed and `(...)` represents a union.

Planned compression heuristics
---

*Compressing Long Strings*
String values longer than some configured length are compressed to `char[]` based on the assumption that it is unlikely long strings will provide much useful categorical information (e.g. the body of a news article or pages of a book).

*Map Key Range Compression*
When the ratio of the number of keys in a map to the number of observations is > ε, attempt to group literal keys by their type and compress to `Type, [min, max]`. If there are multiple clusters, just compress the largest. A lower bound on the number of observations would also be specified to avoid overly aggressive compression, e.g. don't consider this heuristic until there are at least 100 keys in the map.

*Value Range Compression*
Similar to map key range compression, this heuristic would compress unions of values by grouping by their type and replacing the group with `Type, [min, max]`. Configurable via minimum size threshold and ratio of ||values|| to ||observations||.

Other ideas for compression heuristics
---

*Outlier Elimination*
Elide values appearing very infrequently in the dataset where "very infrequently" is a configurable threshold (e.g. less than 1% of documents).

*Outlier LUB*
Compress outliers to their least-upper-bound.

*Literal string compression*
Preserve more string literals, but use a known string compression scheme to compress their representation. Not sure how useful this would be, but might allow users to only pay the space cost of large strings when they care about their contents.

*Similar Strings*
Combine string literals that are "near" each other, according to a distance function, within a configurable threshold. Maybe this would only apply to outliers that are "near" a frequent sibling (indicating maybe they're a misspelling or typo).

Optimization
---

One idea on how to optimize compression is to allow users to supply a space bound on the representation, e.g. limit it to at most 10kb. We then might be able to use the entropy of the SST as a cost function and an optimization algorithm to minimize entropy while remaining within the cost bound. I'm not sure how feasible this is or how much of an effect it would have on latency, though I'd expect sampling the dataset to be the dominant factor there. However, this technique might also prevent incremental compression as the optimization algorithm would want to try different choices of compression parameters to minimize cost.

We could also allow users to indicate they don't need certain information. They could indicate they don't want any literals, so they'd then all be compressed to their type. Or that they just aren't interested in string literals or nulls, for instance.

Another possibility is to come up with sets of parameter values that we label as "levels", so users could ask for "high" or "low" compression, or maybe a range from 1-5, for example. Each label would select a set of parameters more or less aggressive relative to the other labels.

**Comment by wemrysi** [comment]
@jdegoes I'd appreciate any comments/ideas you might have regarding the above, thanks!

**Comment by wemrysi** [comment]
@jdegoes Thanks, the feedback is appreciated.

Regarding lossiness, how will the frontend determine the bound? Will it try various values until it arrives at the desired result? I ask as, say we're using bits to describe information content, how does the frontend know it wants to bound at 1kb and not 10kb without knowing what the data looks like? It seems like some context is required to make the decision.

Providing accuracy information and distributions sounds good, are they both needed for the initial version or can they be added in a future iteration?

**Comment by jdegoes** [comment]
@wemrysi It will be determined by the intended use of the data. For example, in a dropdown list, the front-end will need extreme lossiness, because it has space to show only a handful of variants before usability suffers; while in a structure editor, much more precision can be used because only a part of the structure is visible at any time.

Other notions could be used, too: for example, measures of how wide (product), deep (depth), and broad (sum) the SST is. Fundamentally, the front-end wants to show as much information as it possibly can given the limitations of the way it is displaying the information. 

We can add other features such as accuracy and histograms in the future.
