### ISSUE TITLE
First demoability of fallback evaluator

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#2069]
This ticket will be complete when we 

- [ ] enable the first integration test for the fallback evaluator
- [ ] can run a basic query against the fallback evaluator in SlamData

**Comment by djspiewak** [comment]
First demo query is probably going to be `select count(*) from foo`.  So we need:

- [ ] Data ingest
- [ ] An implementation of `Read`
- [ ] Some basic QScript traversal and implementation as `TransSpec1`
- [ ] The ability to reduce, at least at a hacky first-order level
- [ ] An understanding of where the `count` function is
