### ISSUE TITLE
Implement the rest of qscriptcore

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2266]
- [x] `Filter`
- [ ] `Reduce`
  + [x] Assume provenance order 1 first (#2439) 
  + [ ] Higher order depends on #1990 
- [ ] `Sort`
  + [x] Assume provenance order 1 first (#2518)
  + [ ] Higher order depends on #1991
- [x] `Union`
- [x] `LeftShift` (delegated to #1988)
