### ISSUE TITLE
Implement new Precog VFS

### ISSUE THREAD

**Issue by djspiewak** [quasar-analytics/quasar#2334]
The existing VFS abstraction is leaky, non-atomic and doesn't meet the needs of quasar.  We can do a lot better.  This will entail:

- [ ] Implementing an interface like [this one](https://gist.github.com/djspiewak/ca5cd6eea852a260e2bf8720016fb801)
- [*] Designing a VFS file structure with the appropriate properties
  + [ ] Documenting
  + [ ] Implementing
    * [ ] Implementing an actually-atomic `VersionLock`
- [ ] Hacking out a better `Free` testing utility
- [ ] Reimplementing `Table#load` in terms of the new VFS

Closes #2320
