### ISSUE TITLE
Ensuring Spark-Family of Connectors are demoable at demo.sd.slamdata.com

### ISSUE THREAD

**Issue by zeeiyerWork** [quasar-analytics/quasar#2469]
Below list prioritised: 

- [x] create **fully** distributed HDFS file system
- [x] install quasar on serv1
- [x] put examples on hdfs
- [x] create spark cluster

Here is list of examples on demo environment 

| Works?               | Example name                                 | Comment  |
| --------------- | --------------------------------- | ---------- |
| :+1:                     | Conditional Input                              |                   |
| :+1:                     | Data Types                                        |                   |
| :+1:                     | Flights Cost                                       |                   |
| :+1:                     | IOT Sensors Report                      |                   |
| :+1:                     | Markdown Examples   |                   |
| :+1:                     | Revenue Distribution   |                   |
|  :+1:                    | Olympics Filter and Download |                 |
|  :+1:                    | Olympics Search and Download |               |
| 👍                        | Geo Heatmap State Comparison |                |
| 👍                        | Geo Markers - Texas |               |

**Comment by rabbitonweb** [comment]
@zeeiyerWork this is done, however:

1. there are demos that are not working because of qscript or frontend issues, does it mean they block this issue (label it blocked) or do we close it regardlessly?
2. serv1 is being closed (for the reasons that I don't quite get) so the question one more time: given this fact, does it qualify this issue to be closed then?

**Comment by zeeiyerWork** [comment]
@rabbitonweb - What is the story with the ? What needs to happen there.

**Comment by rabbitonweb** [comment]
@zeeiyerWork the "Customer Orders by State (markdown)" should not be on this table - i'm removing it

**Comment by zeeiyerWork** [comment]
@rabbitonweb any progress over the last 12 days ??? 
As per frontend https://github.com/slamdata/slamdata/issues/2142 , https://github.com/slamdata/slamdata/issues/2372, https://github.com/slamdata/slamdata/issues/2373 and https://github.com/slamdata/slamdata/issues/2373 are all fixed (some several days ago)?

**Comment by rabbitonweb** [comment]
Did not realize those were fixed, will update right away and see what's the progress on it

**Comment by rabbitonweb** [comment]
two issues moved to 👍 , next to will require some investigation with me  & @dugdun

**Comment by rabbitonweb** [comment]
Closing this issue, demo env. is ready for show. There are some workspaces that are missing, but adding them is blocked by external issues. Those are:
1. https://github.com/quasar-analytics/quasar/issues/3104
2. https://github.com/quasar-analytics/quasar/issues/3105
3. https://github.com/quasar-analytics/quasar/issues/3106
4. https://github.com/quasar-analytics/quasar/issues/3107
5. https://github.com/quasar-analytics/quasar/issues/3108
