### ISSUE TITLE
Ensure no non-mongo integration tests have regressed in next-major

### ISSUE THREAD

**Issue by alissapajer** [quasar-analytics/quasar#2531]
Following are the non-mongo integration tests that are passing on master but not passing on next-major. 

**Couchbase:**
- [x] demo/timeSeriesAggregation.test (#2571)

**MarkLogic XML:**
- [x] different-flattens.test (#2602)
- [x] unifyFlattenedFieldsWithUnflattened.test (#2610)

**MarkLogic JSON:**
- [x] unifyFlattenedFieldsWithUnflattened.test (#2610)

**Spark:**
- [x] different-flattens.test (#2602)
- [x] orderedWildcardWithProjection.test (enabled in #2702)
- [x] sortWildcardOnExpression.test (enabled in #2702)
- [x] unifyFlattenedFieldsWithUnflattened.test (#2610)
- [x] demo/nestedSelectWithReduce.test (enabled in #2700)
- [x] demo/timeSeriesAggregation.test

**Comment by alissapajer** [comment]
For posterity, compiled these lists using
```
$ ag -l '(\"spark_local\":[ \t]*\"pending)|(\"spark_local\":[ \t]*\"skip)|(\"spark_local\":[ \t]*\"timeout)' it/src/main/resources/tests/*.test it/src/main/resources/tests/*/*.test
```
and then diffing the results against master using `grep -Fvf`.

**Comment by alissapajer** [comment]
Removing the `topic: CI (Travis)` label since these failures don't have anything to do with Travis. They are legitimate regressions in tests against various connectors.

**Comment by djspiewak** [comment]
There's going to be quite a few mimir tests regressing without an implementation of #2681.  I would propose that we consider such tests to be out of scope for the next-major merge, since they will come back to life with the resolution of that issue.

**Comment by alissapajer** [comment]
@djspiewak I just navigated to this issue to make _exactly_ that same comment. So :+1:.
