### ISSUE TITLE
Eliminate Query Regressions in QScript-based MongoDB Connector

### ISSUE THREAD

**Issue by wemrysi** [quasar-analytics/quasar#2532]
This issue exists to track the progress of eliminating the regressions, individual regressions will have their own issues and will be associated with the query they're affecting above.

The following queries have regressed in the QScript-based MongoDB connector:

- [x] caseWithGroup.test (#1755, #2847)
- [x] different-flattens.test (#1951, #1929)
- [x] flattenGroupedObject.test (#2359)
- [x] groupByFlatten.test (#2537)
- [x] joins/fullOuterEquiJoin.test (fixed in #2562)
- [x] joins/groupedJoin.test (#2121)
- [x] joins/joinWithComplexCondition.test (fixed in #2562)
- [x] joins/nonJsJoinCondition.test (#2110)
- [x] joins/selfjoinWithComplexCondition.test (fixed in #2562)
- [x] joins/symmetricNonJsJoinCondition.test (#2110)
- [ ] mongodb/fakeObjectId.test (`OID` function not available in QScript)
- [ ] multistageFlatten.test (#2540)
- [ ] multitypeFlatten.test (#2133)
- [ ] temporal/invalidDateFilter.test (#2541)
- [x] undefinedJsInExpr.test (possibly a problem with the test itself, see `FIXME` therein)
- [ ] unifyFlattenedFieldsWithMultipleUses.test (#2366)
- [x] union.test (#2543)

The following queries have regressed (or are not passing) in mongo 2.6 and 3.0, but are passing in mongo 3.2 and 3.4:

- [ ] basicAnalyticQuery.test (pre-3.2, #2535)
- [ ] caseVariations.test (#2535, #2785) (pre-3.2 passing with result order ignored)
- [ ] citiesByLargestZip.test (#2535)
- [ ] citiesByTotalPopulation.test (pre-3.2, #2535)
- [ ] concatArrayWithLiteral.test (pre-3.2, #2536)
- [ ] doubleFlatten.test (pre-3.2, #2544)
- [ ] doubleFlattenWithIntervening.test (pre-3.2, #2544)
- [ ] filterSortLimit.test (pre-3.2 passing with result order ignored)
- [ ] flattenArray.test (pre-3.2, #2545)
- [ ] flattenNestedObject.test (pre-3.2, #2545)
- [ ] flattenObject.test (pre-3.2, #2545)
- [ ] joins/orderJoinByAlias.test (#2725 #2785 pre 3.2 passing with result order ignored)
- [ ] largestCities.test (pre-3.2, #2535)
- [ ] largestZips.test (pre 3.2 passing with result order ignored)
- [ ] mongodb/temporal/time.test (2.6-only, #2539)
- [ ] orderByIfUndefined.test (pre 3.2 passing with result order ignored)
- [ ] orderedWildcardWithProjection.test (#2785 pre 3.2 passing with result order ignored)
- [ ] sortByJS.test (pre 3.2 passing with result order ignored)
- [ ] shortCities.test (pre 3.2 #2535, passing with result order ignored)
- [ ] sortProjectLimit.test (pre 3.2 passing with result order ignored)
- [ ] sortWildcardOnExpression.test (#2785 pre 3.2 passing with result order ignored)
- [ ] tripleFlatten.test (pre-3.2, #2544)
- [ ] unifyFlattenedFieldsWithUnflattened.test (#2331, #2366, #2535)  (pre 3.2 passing with result order ignored)
- [ ] wildcardWithSort.test (pre 3.2 passing with result order ignored)

**Comment by alissapajer** [comment]
Closing, as these tests are all tracked by individual issues.
