### ISSUE TITLE
Avoid `mapReduce` for `Sort` (phase 1)

### ISSUE THREAD

**Issue by jsantos17** [quasar-analytics/quasar#2884]
Consider the QScript for this query as planned on [current master](https://github.com/quasar-analytics/quasar/commit/e27a94cae377705e6dc1ee13656b6cd0df246b18):

```sql
select * from zips order by pop
```

The QScript handed to the Mongo connector:

```
QScript (Optimized):
Map
├─ Sort
│  ├─ ShiftedRead(/jps/zips, ExcludeId)
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ╰─ Ascending
│        ╰─ By
│           ╰─ Guard
│              ├─ ○
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ○
│              │  ╰─ Constant(Str(pop))
│              ╰─ Undefined
╰─ Guard
   ├─ ○
   ├─ Type(Obj(Map[], Some(Top)))
   ├─ ○
   ╰─ Undefined
```

After `mapBeforeSort`, the tree is transformed into

```
QScript (Mongo-specific):
Map
├─ Sort
│  ├─ Map
│  │  ├─ ShiftedRead(/jps/zips, ExcludeId)
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ ○
│  │     ╰─ MakeArray
│  │        ╰─ ○
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ╰─ Ascending
│        ╰─ By
│           ╰─ Guard
│              ├─ ProjectIndex
│              │  ├─ ○
│              │  ╰─ Constant(Int(1))
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ProjectIndex
│              │  │  ├─ ○
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Str(pop))
│              ╰─ Undefined
╰─ ProjectIndex
   ├─ ○
   ╰─ Constant(Int(0))
```

`assumeReadType` is then applied to the tree. This is a nop since the transformed tree does not contain any `Guard`s for `Type(Obj(Map[], Some(Top)))` on `Hole`.

This plan is overtly complex and forces us into `mapReduce` ~~due to the  `Guard` for `Type(Obj(Map[], Some(Top)))` not on `Hole`.~~  "due to the fact that we only implement ProjectField in aggregation when we're projecting directly from a var, here we're projecting the result of ProjectIndex which forces the map-reduce"

After discussion with @alissapajer, we agree we could instead apply `assumeReadType` and `Rewrite.normalize` before `mapBeforeSort`.  This would yield:

```
QScript:
Sort
├─ ShiftedRead(/jps/zips, ExcludeId)
├─ Bucket
│  ╰─ List
╰─ Order
   ╰─ Ascending
      ╰─ By
         ╰─ ProjectField
           ├─ ○
           ╰─ Constant(Str(pop))
```

After this, `mapBeforeSort` would have no effect on the query and we'd  be closer to achieving parity with old Mongo.

All in all, the proposed solution would apply the transformations in this order:

1. `assumeReadType`
2. `Rewrite.normalize`
3. `mapBeforeSort`

Note that we currently don't apply `assumeReadType` to the `FreeMap`s in the `Sort` node. We also need to do this for the issue to be resolved.

Branched off #2667 

====

Task list

- [x] [assumeReadType across Branches and apply to Sort](https://github.com/quasar-analytics/quasar/pull/3001)
- [ ] [Only apply `mapBeforeSort` when necessary (in progress)](https://github.com/quasar-analytics/quasar/pull/3029)
- [ ] [Sorting query on _id does not work properly on mongo agg.pipeline](https://github.com/quasar-analytics/quasar/issues/3007)

**Comment by wemrysi** [comment]
I don't think map-reduce is due to the `Guard` itself, but due to the fact that we only implement `ProjectField` in aggregation when we're projecting directly from a `var`, here we're projecting the result of `ProjectIndex` which forces the map-reduce.

**Comment by jsantos17** [comment]
@wemrysi Thanks for the correction. I have updated the issue.

**Comment by jsantos17** [comment]
I checked this and looks like it's mostly fixed after #2892 was fixed. We're still not traversing the `FreeMap` for the sort keys with `assumeReadType`, so the workflow has an extra, unnecessary `$ProjectF` in it. The new workflow for the query:

```
Workflow (crystallized):
Chain
├─ $ReadF(jps; zips)
├─ $ProjectF
│  ├─ Name("0" -> {
│  │       "$cond": [
│  │         {
│  │           "$and": [
│  │             { "$lte": [{ "$literal": {  } }, "$$ROOT"] },
│  │             { "$lt": ["$$ROOT", { "$literal": [] }] }]
│  │         },
│  │         "$pop",
│  │         { "$literal": undefined }]
│  │     })
│  ├─ Name("src" -> "$$ROOT")
│  ╰─ ExcludeId
├─ $SortF
│  ╰─ SortKey(0 -> Ascending)
╰─ $ProjectF
   ├─ Name("__quasar_mongodb_sigil" -> "$src")
   ╰─ ExcludeId
```

**Comment by jsantos17** [comment]
Other queries exhibiting similar behavior:

```sql
select bar from foo order by bar
```

<details>
<summary> QScript </summary>

```
Map
├─ Sort
│  ├─ Map
│  │  ├─ ShiftedRead(/db/foo, ExcludeId)
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ ProjectField
│  │     │     ├─ ○
│  │     │     ╰─ Constant(Str(bar))
│  │     ╰─ MakeArray
│  │        ╰─ ○
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ╰─ Ascending
│        ╰─ By
│           ╰─ Guard
│              ├─ ProjectIndex
│              │  ├─ ○
│              │  ╰─ Constant(Int(1))
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ProjectIndex
│              │  │  ├─ ○
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Str(bar))
│              ╰─ Undefined
╰─ ProjectIndex
   ├─ ○
   ╰─ Constant(Int(0))
```
 </details>

---

```sql
select name from person order by height
```

<details>
<summary>QScript</summary>

```
Map
├─ Sort
│  ├─ Map
│  │  ├─ ShiftedRead(/db/foo, ExcludeId)
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ MakeMap
│  │     │     ├─ Constant(Str(name))
│  │     │     ╰─ ProjectField
│  │     │        ├─ ○
│  │     │        ╰─ Constant(Str(name))
│  │     ╰─ MakeArray
│  │        ╰─ ○
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ╰─ Ascending
│        ╰─ By
│           ╰─ Guard
│              ├─ ProjectIndex
│              │  ├─ ○
│              │  ╰─ Constant(Int(1))
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ProjectIndex
│              │  │  ├─ ○
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Str(height))
│              ╰─ Undefined
╰─ ProjectIndex
   ├─ ○
   ╰─ Constant(Int(0))
```

</details>

---

```sql
select city, pop from zips where pop <= 1000 order by pop desc, city
```

<details>
<summary>QScript</summary>

```
QScript Mongo (Shuffle Maps):
Map
├─ Sort
│  ├─ Map
│  │  ├─ Filter
│  │  │  ├─ ShiftedRead(/jps/zips, ExcludeId)
│  │  │  ╰─ Guard
│  │  │     ├─ ProjectField
│  │  │     │  ├─ ○
│  │  │     │  ╰─ Constant(Str(pop))
│  │  │     ├─ Type(Int, Dec, Interval, Str, Timestamp, Date, Time, or Bool)
│  │  │     ├─ Lte
│  │  │     │  ├─ ProjectField
│  │  │     │  │  ├─ ○
│  │  │     │  │  ╰─ Constant(Str(pop))
│  │  │     │  ╰─ Constant(Int(1000))
│  │  │     ╰─ Undefined
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ ConcatMaps
│  │     │     ├─ MakeMap
│  │     │     │  ├─ Constant(Str(city))
│  │     │     │  ╰─ ProjectField
│  │     │     │     ├─ ○
│  │     │     │     ╰─ Constant(Str(city))
│  │     │     ╰─ MakeMap
│  │     │        ├─ Constant(Str(pop))
│  │     │        ╰─ ProjectField
│  │     │           ├─ ○
│  │     │           ╰─ Constant(Str(pop))
│  │     ╰─ MakeArray
│  │        ╰─ ○
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ├─ Descending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ○
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(pop))
│     │        ╰─ Undefined
│     ╰─ Ascending
│        ╰─ By
│           ╰─ Guard
│              ├─ ProjectIndex
│              │  ├─ ○
│              │  ╰─ Constant(Int(1))
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ProjectIndex
│              │  │  ├─ ○
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Str(city))
│              ╰─ Undefined
╰─ ProjectIndex
   ├─ ○
   ╰─ Constant(Int(0))
```

</details>

---

```sql
select * from zips order by pop, city desc
```

<details>
<summary>QScript</summary>

```
QScript Mongo (Prefer Projection):
Map
├─ Sort
│  ├─ Map
│  │  ├─ ShiftedRead(/jps/zips, IncludeId)
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ Guard
│  │     │     ├─ ProjectIndex
│  │     │     │  ├─ ○
│  │     │     │  ╰─ Constant(Int(1))
│  │     │     ├─ Type(Obj(Map[], Some(Top)))
│  │     │     ├─ ProjectIndex
│  │     │     │  ├─ ○
│  │     │     │  ╰─ Constant(Int(1))
│  │     │     ╰─ Undefined
│  │     ╰─ MakeArray
│  │        ╰─ ○
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ProjectIndex
│     │        │  │  │  ├─ ○
│     │        │  │  │  ╰─ Constant(Int(1))
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(pop))
│     │        ╰─ Undefined
│     ╰─ Descending
│        ╰─ By
│           ╰─ Guard
│              ├─ ProjectIndex
│              │  ├─ ProjectIndex
│              │  │  ├─ ○
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Int(1))
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ProjectIndex
│              │  │  ├─ ProjectIndex
│              │  │  │  ├─ ○
│              │  │  │  ╰─ Constant(Int(1))
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Str(city))
│              ╰─ Undefined
╰─ ProjectIndex
   ├─ ○
   ╰─ Constant(Int(0))
```

</details>

---

```sql
select * from zips order by pop, state, city, a4, a5, a6
```

<details>
<summary>QScript</summary>

```
QScript Mongo (Prefer Projection):
Map
├─ Sort
│  ├─ Map
│  │  ├─ ShiftedRead(/jps/zips, IncludeId)
│  │  ╰─ ConcatArrays
│  │     ├─ MakeArray
│  │     │  ╰─ Guard
│  │     │     ├─ ProjectIndex
│  │     │     │  ├─ ○
│  │     │     │  ╰─ Constant(Int(1))
│  │     │     ├─ Type(Obj(Map[], Some(Top)))
│  │     │     ├─ ProjectIndex
│  │     │     │  ├─ ○
│  │     │     │  ╰─ Constant(Int(1))
│  │     │     ╰─ Undefined
│  │     ╰─ MakeArray
│  │        ╰─ ○
│  ├─ Bucket
│  │  ╰─ List
│  ╰─ Order
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ProjectIndex
│     │        │  │  │  ├─ ○
│     │        │  │  │  ╰─ Constant(Int(1))
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(pop))
│     │        ╰─ Undefined
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ProjectIndex
│     │        │  │  │  ├─ ○
│     │        │  │  │  ╰─ Constant(Int(1))
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(state))
│     │        ╰─ Undefined
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ProjectIndex
│     │        │  │  │  ├─ ○
│     │        │  │  │  ╰─ Constant(Int(1))
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(city))
│     │        ╰─ Undefined
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ProjectIndex
│     │        │  │  │  ├─ ○
│     │        │  │  │  ╰─ Constant(Int(1))
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(a4))
│     │        ╰─ Undefined
│     ├─ Ascending
│     │  ╰─ By
│     │     ╰─ Guard
│     │        ├─ ProjectIndex
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ○
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Int(1))
│     │        ├─ Type(Obj(Map[], Some(Top)))
│     │        ├─ ProjectField
│     │        │  ├─ ProjectIndex
│     │        │  │  ├─ ProjectIndex
│     │        │  │  │  ├─ ○
│     │        │  │  │  ╰─ Constant(Int(1))
│     │        │  │  ╰─ Constant(Int(1))
│     │        │  ╰─ Constant(Str(a5))
│     │        ╰─ Undefined
│     ╰─ Ascending
│        ╰─ By
│           ╰─ Guard
│              ├─ ProjectIndex
│              │  ├─ ProjectIndex
│              │  │  ├─ ○
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Int(1))
│              ├─ Type(Obj(Map[], Some(Top)))
│              ├─ ProjectField
│              │  ├─ ProjectIndex
│              │  │  ├─ ProjectIndex
│              │  │  │  ├─ ○
│              │  │  │  ╰─ Constant(Int(1))
│              │  │  ╰─ Constant(Int(1))
│              │  ╰─ Constant(Str(a6))
│              ╰─ Undefined
╰─ ProjectIndex
   ├─ ○
   ╰─ Constant(Int(0))
```

</details>

---

In all of these the `Map` is duplicated after `mapBeforeSort` is applied to the tree. Given how simple these are we should address this issue soon.
